import Fastify from 'fastify';
import cors from '@fastify/cors';
import jwt from '@fastify/jwt';

// Simple server for demonstration
const server = Fastify({
  logger: true
});

// Register plugins
async function start() {
  try {
    // CORS
    await server.register(cors, {
      origin: ['http://localhost:12000', 'https://work-1-roxfgucnxgorzqzm.prod-runtime.all-hands.dev'],
      credentials: true,
    });

    // JWT
    await server.register(jwt, {
      secret: 'your-super-secret-jwt-key-change-in-production-heirloom-2024'
    });

    // Authentication decorator
    server.decorate('authenticate', async function (request: any, reply: any) {
      try {
        await request.jwtVerify();
      } catch (err) {
        reply.send(err);
      }
    });

    // Health check
    server.get('/health', async (request, reply) => {
      return {
        status: 'healthy',
        service: 'heirloom-backend',
        timestamp: new Date().toISOString(),
        version: '1.0.0'
      };
    });

    // Auth routes
    server.post('/api/auth/login', async (request, reply) => {
      const { email, password } = request.body as { email: string; password: string };
      
      if (email && password) {
        const token = await reply.jwtSign({ 
          email,
          id: 'demo-user-id',
          role: 'user'
        });
        
        return {
          success: true,
          token,
          user: {
            id: 'demo-user-id',
            email,
            firstName: 'Demo',
            lastName: 'User'
          }
        };
      }
      
      return reply.status(401).send({
        success: false,
        message: 'Invalid credentials'
      });
    });

    // Demo constellation data
    server.get('/api/memories/constellation', async (request, reply) => {
      return {
        memories: [
          {
            id: '1',
            title: 'Wedding Day',
            type: 'milestone',
            x: 0,
            y: -150,
            connections: ['2', '3'],
            timestamp: new Date('2020-06-15'),
            importance: 5,
            preview: '💒'
          },
          {
            id: '2',
            title: 'First Child Born',
            type: 'milestone',
            x: -120,
            y: -80,
            connections: ['1', '4'],
            timestamp: new Date('2021-03-22'),
            importance: 5,
            preview: '👶'
          },
          {
            id: '3',
            title: 'Family Vacation',
            type: 'photo',
            x: 120,
            y: -80,
            connections: ['1', '5'],
            timestamp: new Date('2020-08-10'),
            importance: 4,
            preview: '🏖️'
          }
        ]
      };
    });

    // AI story generation demo
    server.post('/api/ai/generate-story', async (request, reply) => {
      const { memoryIds, style = 'narrative' } = request.body as { memoryIds: string[]; style?: string };
      
      // Simulate AI processing time
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      return {
        story: {
          title: 'A Beautiful Family Journey',
          content: `This is a demo AI-generated story based on your selected memories. In a real implementation, this would be generated by Llama 4 AI based on the actual memory content and connections.

The story would weave together the memories you selected (${memoryIds.join(', ')}) into a cohesive narrative that captures the essence of your family's journey.

This revolutionary platform uses advanced AI to transform your precious memories into beautiful stories that will be treasured by future generations.`,
          confidence: 0.92,
          generationTime: 2000
        }
      };
    });

    // Start server
    const address = await server.listen({
      port: 3001,
      host: '0.0.0.0'
    });
    
    console.log(`🚀 Heirloom backend running at ${address}`);
    console.log(`🌟 Building the future of legacy preservation...`);
    
  } catch (error) {
    console.error('Failed to start server:', error);
    process.exit(1);
  }
}

start();